---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8010/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
      defaultZone: http://localhost:8010/eureka/
    

---
spring:
  profiles: subject
words: I,You,He,She,It,We,They
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
---
spring:
  profiles: name
words: Augusto,Huapaya

---
mensaje: Se encontró la lista de personas exitosamente

---
errormsg: No se encontro datos para el dni:


