---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8010/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
words: Nombre1,Nombre2,Nombre3,Nombre4,Nombre5
  
---
spring:
  profiles: verb
words: Apellido1,Apellido2,Apellido3,Apellido4,Apellido5

---
spring:
  profiles: name
words: 00000001,00000002,00000003,00000004,00000005
