---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8010/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
      defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
words: Augusto,Raul
  
---
spring:
  profiles: verb
words: Huapaya,Romero
